package rocks.blackblock.polyvalent;

import io.github.theepicblock.polymc.api.PolyMap;
import io.github.theepicblock.polymc.api.PolyMcEntrypoint;
import io.github.theepicblock.polymc.api.PolyRegistry;
import io.github.theepicblock.polymc.api.block.BlockStateProfile;
import io.github.theepicblock.polymc.api.misc.PolyMapProvider;
import io.github.theepicblock.polymc.impl.PolyMcCommands;
import io.github.theepicblock.polymc.impl.generator.Generator;
import net.fabricmc.api.DedicatedServerModInitializer;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.fabricmc.loader.api.FabricLoader;
import net.luckperms.api.LuckPerms;
import net.luckperms.api.LuckPermsProvider;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import rocks.blackblock.polyvalent.block.PolyvalentBlock;
import rocks.blackblock.polyvalent.networking.TempPlayerLoginAttachments;
import rocks.blackblock.polyvalent.polymc.PolyvalentGenerator;
import rocks.blackblock.polyvalent.polymc.PolyvalentMap;
import rocks.blackblock.polyvalent.polymc.PolyvalentRegistry;
import rocks.blackblock.polyvalent.server.PolyvalentCommands;

import java.util.HashMap;
import java.util.List;

public class PolyvalentServer implements DedicatedServerModInitializer {

    private static PolyvalentMap map = null;
    private static LuckPerms luckPerms = null;
    private static Boolean triedLuckPerms = false;

    // The profile to use for full material blocks
    public static final BlockStateProfile WOOD_BLOCK_PROFILE = Polyvalent.createBlockStateProfile("polyvalent_material_block", Polyvalent.WOOD_BLOCK);
    public static final BlockStateProfile GLOW_BLOCK_PROFILE = Polyvalent.createBlockStateProfile("glow_material_block", Polyvalent.GLOW_BLOCK);
    public static final BlockStateProfile STONE_BLOCK_PROFILE = Polyvalent.createBlockStateProfile("stone_material_block", Polyvalent.STONE_BLOCK);
    public static final BlockStateProfile GLASS_BLOCK_PROFILE = Polyvalent.createBlockStateProfile("glass_material_block", Polyvalent.GLASS_BLOCK);
    public static final BlockStateProfile LEAVES_BLOCK_PROFILE = Polyvalent.createBlockStateProfile("leaves_block", Polyvalent.LEAVES_BLOCK);

    public static final HashMap<String, Integer> BLOCK_STATE_ID_MAP = new HashMap<>();

    public static boolean hasLuckPerms() {
        if (luckPerms != null) {
            return true;
        }

        return FabricLoader.getInstance().isModLoaded("luckperms");
    }

    public static LuckPerms getLuckPerms() {

        if (!triedLuckPerms && luckPerms == null) {
            triedLuckPerms = true;
            try {
                if (FabricLoader.getInstance().isModLoaded("luckperms")) {
                    luckPerms = LuckPermsProvider.get();
                }
            } catch (Exception e) {
                Polyvalent.log("Failed to load LuckPerms! Polyvalent will not be able to use it.");
            }
        }

        return luckPerms;
    }

    /**
     * Generate our own polymap
     *
     * @deprecated this is an internal method you shouldn't call.
     */
    public static void generatePolyMap() {

        if (map != null) {
            throw new IllegalStateException("Polyvalent PolyMap already generated!");
        }

        Polyvalent.log("Generating Polyvalent map...");

        PolyvalentRegistry registry = new PolyvalentRegistry();

        // Register default global ItemPolys
        PolyvalentGenerator.addDefaultGlobalItemPolys(registry);

        // Let mods register polys via the api
        List<PolyMcEntrypoint> entrypoints = FabricLoader.getInstance().getEntrypoints("polymc", PolyMcEntrypoint.class);
        for (PolyMcEntrypoint entrypointEntry : entrypoints) {
            entrypointEntry.registerPolys(registry);
        }

        // Auto generate the rest
        PolyvalentGenerator.generateMissing(registry);

        map = registry.build();

        Polyvalent.log("Finished generated Polyvalent map");
    }

    /**
     * Returns the polymap built with Polyvalent
     *
     * @return the main PolyMap generated by polyvalent
     */
    @Deprecated
    public static PolyvalentMap getMainMap() {
        if (map == null) {
            throw new NullPointerException("Tried to access the PolyMap before it was initialized");
        }
        return map;
    }

    @Override
    public void onInitializeServer() {

        if (!FabricLoader.getInstance().isModLoaded("polymc")) {
            throw new IllegalStateException("Polyvalent must be used together with PolyMc on the server");
        }

        Polyvalent.log("Registering Polyvalent commands...");

        PolyvalentCommands.registerCommands();

        PolyMapProvider.EVENT.register(player -> {
            TempPlayerLoginAttachments player_login = (TempPlayerLoginAttachments) player;

            if (player_login.hasPolyvalent()) {
                return player_login.getPolyvalentMap();
            }

            return null;
        });

        int number = -1;

        Polyvalent.log("Registering all block states...");

        // Create a map to all the state ids
        for (BlockState state : Block.STATE_IDS) {
            Block block = state.getBlock();

            number++;

            //System.out.println("[Polyvalent] State: " +  number + "  »»  " + state);

            if (block instanceof PolyvalentBlock) {
                String state_name = state.toString();
                int id = Block.STATE_IDS.getRawId(state);
                BLOCK_STATE_ID_MAP.put(state_name, id);
            }
        }

        Polyvalent.log("Finished registering all block states");
    }

}
